version: "3"
services:
  opf_client:
    build:
      context: ./
    image: ghcr.io/opendrugdiscovery/openfractal-client:dev-local
    environment:
      # Server
      QCA_FRACTAL_URI: http://127.0.0.1:7777
      QCA_USERNAME: compute_user
      QCA_PASSWORD: compute_password
      QCA_VERIFY: false
      # Manager
      MANAGER_NAME: demo_manager
      QUEUE_TAGS: '["demo_local"]'
      # Common
      QCA_ADAPTER: pool
      QCA_TASKS_PER_WORKER: 1
      QCA_CORES_PER_WORKER: 16
      QCA_MEMORY_PER_WORKER: 16
      QCA_MAX_WORKERS: 4
      QCA_RETRIES: 5
