server:
  fractal_uri: https://openfractal-test-pgzbs3yryq-uc.a.run.app
  username: compute_user
  password: compute_password
  verify: false

manager:
  manager_name: manager_demo_local
  queue_tag: ["demo_local"]

common:
  adapter: pool
  tasks_per_worker: 1
  cores_per_worker: 8
  memory_per_worker: 16
  max_workers: 4
  retries: 2
