server:
  fractal_uri: https://openfractal-test-pgzbs3yryq-uc.a.run.app
  username: YOUR_USERNAME
  password: YOUR_PASSWORD

manager:
  # The name of the manager is used to identify the manager in the database.
  # It's not unique but for each manager launched a unique name will be computed
  # by the server.
  manager_name: manager_demo_local
  # Tags are used to filter the tasks that will be sent to the manager.
  queue_tag: ["demo_local"]


common:
  adapter: pool
  tasks_per_worker: 1
  cores_per_worker: 8
  memory_per_worker: 16
  max_workers: 4
  retries: 2
